### ISSUE TITLE
Recommendation (BE)

### ISSUE THREAD

**Issue by Rionase** [Rionase/BE_Terbangin#2]

**Comment by Rionase** [comment]
ink Merge Request : https://github.com/Rionase/BE_Terbangin/pull/4
Link Branch : https://github.com/Rionase/BE_Terbangin/tree/Nicholas-Recomendation(BE)
Commit : 75d0a0bc09f96c0f3de4f0355a76a5f44b7845a0

**Comment by Resolt123** [comment]
Membuat sebuah API yang dapat memberikan data penerbangan rekomendasi dan juga terfilter sesuai dengan benua.

API Rekomendasi Penerbangan: http://localhost:3000/api/v1/flight/continent
